# 1. 서버 배포 설정 (서버 3개 띄우기)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-deployment
spec:
  replicas: 3             # ★ 핵심: 서버를 3개 복제해서 실행 (안정성 확보)
  selector:
    matchLabels:
      app: travel-app
  template:
    metadata:
      labels:
        app: travel-app
    spec:
      containers:
      - name: travel-server
        image: travel-app:latest  # 우리가 만들 이미지
        imagePullPolicy: Never    # 인터넷 다운로드 없이 내 컴퓨터 이미지 사용
        ports:
        - containerPort: 3000

---
# 2. 서비스 설정 (외부 접속 통로)
apiVersion: v1
kind: Service
metadata:
  name: travel-service
spec:
  type: LoadBalancer
  selector:
    app: travel-app
  ports:
    - port: 3000          # 접속 포트
      targetPort: 3000